##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://ericafindley.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /erica-testcollectionbuilder-repository
# location of code, the full url to your github repository
source-code: https://github.com/ericafindley/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Portland Brew Stories
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: a practice site by Erica Findley
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "With help from our friends in the local brewing community, Multnomah County Library has assembled one of the most comprehensive collections of digital materials related to one of our area's most important and defining industries. This online exhibition tells the story of breweries in Portland. It includes photographs, labels, keg taps, ephemera and video interviews from local breweries within the geographic areas served by our library."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: ericafindley

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: ericapscollectionbuildermetadata03

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
